---
- name: deploy.yml
  hosts: test_bucketeer_servers,prod_bucketeer_servers,prod_sinai_bucketeer_servers

  vars:
    docker_user: dockeradmin
    docker_user_home: /home/dockeradmin
    docker_compose_bin: /usr/local/bin/docker-compose
    dockerhub_tag: latest

  tasks:
    - name: "Upload docker compose environment variables"
      template:
        src: "templates/bucketeer.env.j2"
        dest: "{{ docker_user_home }}/bucketeer/bucketeer.env"
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0644"
      vars:
        # Allow main bucketeer to use bucketeer_large as a batch endpoint
        bucketeer_large: true

    - block:
      - name: "Upload docker compose environment variables for large batch instance"
        template:
          src: "templates/bucketeer.env.j2"
          dest: "{{ docker_user_home }}/bucketeer/bucketeer_large.env"
          owner: "{{ docker_user }}"
          group: "{{ docker_user }}"
          mode: "0644"

    - name: "Update docker-compose.yml file"
      template:
        src: "templates/docker-compose.yml.j2"
        dest: "{{ docker_user_home }}/bucketeer/docker-compose.yml"
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0644"

    - name: "Shutting down running containers"
      shell: |
        {{ docker_compose_bin }} --compatibility down
      args:
        chdir: "{{ docker_user_home }}/bucketeer"
      become: yes
      become_user: "{{ docker_user }}"

    - name: "Pulling new bucketeer image"
      shell: |
        {{ docker_compose_bin }} --compatibility pull
      args:
        chdir: "{{ docker_user_home }}/bucketeer"
      become: yes
      become_user: "{{ docker_user }}"

    - name: "Launch new bucketeer container"
      shell: |
        {{ docker_compose_bin }} --compatibility up -d
      args:
        chdir: "{{ docker_user_home }}/bucketeer"
      become: yes
      become_user: "{{ docker_user }}"

    - name: Check if prod bucketeer site is online
      uri:
        url: "https://bucketeer.library.ucla.edu/status"
        status_code: 200
        validate_certs: false
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
      when: "'prod_bucketeer_servers' in group_names"

    - name: Check if prod sinai bucketeer site is online
      uri:
        url: "https://sinai-bucketeer.library.ucla.edu/status"
        status_code: 200
        validate_certs: false
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
      when: "'prod_sinai_bucketeer_servers' in group_names"


    - name: Check if test bucketeer site is online
      uri:
        url: "https://test-bucketeer.library.ucla.edu/status"
        status_code: 200
        validate_certs: false
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
      when: "'test_bucketeer_servers' in group_names"
