---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==2.2.0

  # Add ansible.cfg to pick up roles path.
#  - "printf '[defaults]\nroles_path = ./' > ansible.cfg"

script:
  # We'll add some commands to test the role here.
  - git clone https://github.com/UCLALibrary/postgresql.git ./uclalib_role_postgres
  - ansible-playbook uclalib_postgres.yml -e postgres-check.yml --syntax-check