---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==2.2.0


script:
  # We'll add some commands to test the role here.
  ansible-playbook uclalib_postgres.yml --syntax-check