- name: iiif_images.yml
  hosts: all
  become: yes
  become_method: sudo
  vars:
    iptables_allowed_input_rules:
      - src_ip: 164.67.0.0/16
        dest_port: 80
        protocol: tcp
      - src_ip: 164.67.0.0/16
        dest_port: 443
        protocol: tcp
      - src_ip: 192.168.60.0/24
        dest_port: 22
        protocol: tcp
      - src_ip: 192.168.60.0/24
        dest_port: 80
        protocol: tcp
      - src_ip: 192.168.60.0/24
        dest_port: 443
        protocol: tcp
      - src_ip: 71.81.250.53
        dest_port: 80
        protocol: tcp
      - src_ip: 71.81.250.53
        dest_port: 443
        protocol: tcp
    smbsrc: //svm-netapp-dlib.in.library.ucla.edu/Masters/DLTempSecure/EMEL
    mountpoint: /sinai/cifsemel
    smbversion: 3.0
  vars_files:
      - /etc/ansible/plays/vars/iptables_library_campusvpn_port80.yml
      - /etc/ansible/plays/vars/iptables_library_campusvpn_port443.yml
      - /etc/ansible/plays/vars/emeluser_smb.yml

  roles:
    - { role: uclalib_role_iiifimages }
    - { role: uclalib_role_iptables, when: ansible_env == "vmware" }
    - { role: uclalib_role_cifsmount, when: ansible_env == "vmware" or ansible_env == 'vagrant' }