- name: ndlcinfo.yml
  become: yes
  hosts: development
  vars:
    iptables_allowed_input_rules:
      - src_ip: 0.0.0.0/0
        dest_port: 80
        protocol: tcp

  roles:
    - { role: uclalib_role_ndlcinfo,		tags: ["ndlc.info"]}
    - { role: uclalib_role_iptables }
