---

- name: uclalib_omicron.yml
  hosts: omicron
  become: true

  roles:
    - name: uclalib_role_firewalld
    - name: uclalib_role_postgresql
      delegate_to: '{{ pgsql_host }}'
    - name: uclalib_role_epel
    - name: uclalib_role_certbot
    - name: uclalib_role_omicron
