---

- name: uclalib_ansible_capdeploy.yml
  become: yes
  become_method: sudo
  hosts: all
  user: ansible

  tasks:
  - name: Ensure ansible user is defined
    set_fact:
      ansible_username: "{{ ansible_user | default('ansible') }}"

  - name: Obtain a fresh clone of the project's git repository
    become_user: "{{ ansible_username }}"
    git:
      repo: "{{ git_repo_url }}"
      dest: "/home/{{ ansible_username }}/{{ project_name }}"
      version: "{{ git_repo_branch }}"

  - name: Install required project gems
    bundler:
      state: present
      chdir: "/home/{{ ansible_username }}/{{ project_name }}"

  - name: Execute capistrano deployment of project
    become_user: "{{ ansible_username }}"
    shell: >
      BRANCH={{ git_repo_branch }} bundle exec cap localhost deploy
    args:
      chdir: /home/{{ ansible_username }}/{{ project_name }}

  - name: Restart Apache HTTPD to reload passenger application
    systemd:
      name: httpd
      state: restarted

  - name: Clean-up ansible user project deploy directory
    file:
      path: "/home/{{ ansible_username }}/{{ project_name }}"
      state: absent

