---

- name: uclalib_craftcms_deploy.yml
  become: yes
  become_method: sudo
  hosts: "{{ deploy_host | default('t-w-craftcms01.library.ucla.edu') }}"

  environment:
    PATH: /opt/rh/rh-php73/root/usr/bin:/opt/rh/rh-php73/root/usr/sbin:{{ ansible_env.PATH }}

  tasks:
    - name: Get PHP executable path 
      command: >
        which php 
      register: php_exec_path

    - name: Set play variables
      set_fact:
        craft_dir: "{{ craft_work_dir | default('/var/www/craftcms') }}"
        craft_user: "{{ craftcms_user | default('craftcms') }}"
        php_exec: "{{ php_exec_path.stdout }}"

    - name: Perform Full Backup of Craft (DB and FS)
      become_user: "{{ craft_user }}"
      command: >
        /usr/local/bin/craftcms_full_backup

    - name: Take CraftCMS System Offline
      become_user: "{{ craft_user }}"
      command: >
        {{ php_exec }} craft off --interactive 0
      args:
        chdir: "{{ craft_dir }}"

    - name: Git pull of code from branch
      become_user: "{{ craft_user }}"
      git:
        repo: "{{ git_repo_url | default('git@github.com:UCLALibrary/craftcms.git') }}"
        dest: "{{ craft_dir }}"
        version: "{{ git_repo_branch | default('main') }}"

    - name: Run composer install to pick-up any package dependency changes
      become_user: "{{ craft_user }}"
      command: >
        {{ php_exec }} craft update/composer-install
      args:
        chdir: "{{ craft_dir }}"

    - name: Run any pending migrations
      become_user: "{{ craft_user }}"
      command: >
        {{ php_exec }} craft migrate/all
      args:
        chdir: "{{ craft_dir }}"

    - name: Apply changes to the Craft project config
      become_user: "{{ craft_user }}"
      command: >
        {{ php_exec }} craft project-config/apply
      args:
        chdir: "{{ craft_dir }}"

    - name: Bring CraftCMS online
      become_user: "{{ craft_user }}"
      command: >
        {{ php_exec }} craft on --interactive 0
      args:
        chdir: "{{ craft_dir }}"
