---

- name: uclalib_icmp_allowed_ipset.yml
  become: yes
  become_method: sudo
  hosts: all

  tasks:
    - name: Put in place icmp_allowed ipset file
      template:
        src: "files/icmp_allowed/icmp_allowed.j2"
        dest: "/etc/firewalld/ipsets/icmp_allowed.xml"
        owner: "root"
        group: "root"
        mode: "0644"
        backup: true
    
    - name: Reload firewalld 
      command: >
        firewall-cmd --reload
