---

- name: uclalib_refresh_solrredisrails.yml
  become: yes
  become_method: sudo
  hosts: all
  user: ansible

  tasks:
  - name: Stop Apache HTTPD
    service:
      name: httpd
      state: stopped

  - name: Delete all content from the Solr index
    command: >
      curl {{ solr_index_url }}/update -H "Content-Type: text/xml" --data-binary '<delete><query>*:*</query></delete>'

  - name: Delete all content in Redis
    command: >
      redis-cli FLUSHALL

  - name: Reset the Rails application database
    become_user: "deploy"
    shell: >
      DISABLE_DATABASE_ENVIRONMENT_CHECK=1 RAILS_ENV=production bundle exec rake db:reset
    args:
      chdir: "/opt/{{ project_name }}/current"

  - name: Start Apache HTTPD
    service:
      name: httpd
      state: started
