---

- name: uclalib_craftcms.yml
  become: yes
  become_method: sudo
  hosts: all

  roles:
    - { role: uclalib_role_firewalld, tags: [firewall] }
    - { role: uclalib_role_postgresql, tags: [psql] }
    - { role: uclalib_role_php, tags: [php] }
    - { role: uclalib_role_apache, tags: [apache] }
    - { role: uclalib_role_redis, tags: [redis] }
    - { role: uclalib_role_craftcms, tags: [craft] }
