---

- name: uclalib_libguidesindexer.yml
  become: yes
  become_method: sudo
  hosts: all

  roles:
    - { role: uclalib_role_pip, tags: [pip] }
    - { role: uclalib_role_libguidesindexer, tags: [libguides] }
