---
- name: uclalib_solr4.yml
  sudo: true
  hosts: solr_master
  # Define the intended solr applicaitons in the vars section below
  # Optionally define the solr instance type and master host fqdn
  vars:
    tomcat_applications:
      - app_name: solr
        shut_port: 8006
        conn_port: 8081
        rproxy_path: solr
    solr_cores:
      - ident: drupal_site_4
        type: 'drupal'
      - ident: livingstone
        type: 'default'
      - ident: oralhistory
        type: 'default'
      - ident: drupal_site_5
        type: 'default'
      - ident: drupal_site_5_dev
        type: 'default'
      - ident: drupal_site_4_dev
        type: 'default'
      - ident: islandora
        type: 'default'
      - ident: www-test
        type: 'drupal'
      - ident: stgall
        type: 'default'
      - ident: www-stage
        type: 'drupal'
      - ident: www
        type: 'drupal'
      - ident: sheetmusic
        type: 'default'
      - ident: jiiify
        type: 'default'
      - ident: sinai
        type: default
    solr_instance_type: 1
#    solr_master_host: t-w-solrmaster01.library.ucla.edu

  roles:
    - { role: uclalib_role_java }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_tomcat }
    - { role: uclalib_role_solr4 }
