---
- name: uclalib_fedora4test.yml
  become: yes
  become_method: sudo
  hosts: fedora4
  vars_files:
    - vars/iptables_library_campusvpn.yml
  vars:
    tomcat_applications:
      - app_name: fedora
        shut_port: 8006
        conn_port: 8081
        rproxy_path: fcrepo

  roles:
    - { role: uclalib_role_java }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_tomcat }
    - { role: uclalib_role_fedora4 }
    - { role: uclalib_role_iptables }
