---
- name: Zabbix Server
  hosts: p-w-zabbix*.library.ucla.edu
  become: yes
  become_method: sudo

  roles:
    - role: uclalib_role_rhelscl
      when: ansible_distribution_major_version == '7'
    - role: uclalib_role_apache
    - role: uclalib_role_certbot
    - role: uclalib_role_postgresql
    - role: uclalib_role_zabbix
    - role: uclalib_role_firewalld
