---

- name: uclalib_craftcms.yml
  become: yes
  become_method: sudo
  hosts: all

  roles:
    - { role: uclalib_role_firewalld }
    - { role: uclalib_role_postgresql }
    - { role: uclalib_role_php }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_redis }
    - { role: uclalib_role_craftcms }
