---

- name: uclalib_rhelfirstbootaws.yml
  become: yes
  become_method: sudo
  hosts: all

  vars:
    zabbix_install_server: false

  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_custom_facts }
    - { role: uclalib_role_rhelinsights }
    - { role: uclalib_role_zabbix }
