---
- name: uclalib_solr.yml
  sudo: true
  hosts: test
  # Define the intended solr applicaitons in the vars section below
  vars:
    tomcat_applications:
      - app_name: solr
        shut_port: 8008
        conn_port: 8083
        rproxy_path: solr

  roles:
    - { role: uclalib_role_java }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_tomcat }
    - { role: uclalib_role_solr }
