- name: localdevplaybook.yml
  hosts: localhost
  connection: localhost
#  become: yes
#  become_method: sudo

  vars:
    ssl: False
    scl: False
    lib_weburl: www-dev.local
#    drush_pub_keys: |
#      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYBUqu5G5+Qmu8mWma8FcjiU8akfChh4kAXKgY4PDeJ29buhyKQlXaAwGrcwe/O3U8Niz7piOJWqkV0nHjvo/oV8BVrjkYzRhkXDhSX52nSHHNqYGuy619/mT4owmaBegTFwiQWWPh/wCYNpzQEX28DOe+4Ekc3gTwHwhjg+vFM3UTFnfg5ikYzhF1O6gz3W9AweGNkPHuIZpY8YH5ROrzreV9K9GIYGRICrHXWYP60JRxYWSITbUvbx40xBKwO85HrnPST2AOv+yrmpfHDEDt8d3ZD4lLbcTAu9rylVPEg63wD6zVw2spzdBp+rmMs9dsP2PBOUdVawId4J0tsN9v cgrzecka@library.ucla.edu
    php_pkgs:
      - php
      - php-ldap
      - php-cli
      - php-xml
      - php-mysql
      - php-pecl-memcache
      - php-pecl-apc
      - php-gd
      - php-mcrypt
      - php-pear
      - php-pdo
      - php-mbstring
      - php-common
# Replacement for php-suhosin? Needs testing
      - php-phpseclib-crypt-hash
    apache_conf:
      pkgs:
        - httpd
      vhost:
        "{{ lib_weburl }}":
          - documentroot: "/opt/www/{{ lib_weburl }}"
          - access_logs: "/etc/httpd/logs/{{ lib_weburl }}-access.log"
          - error_logs: "/etc/httpd/logs/{{ lib_weburl }}-error.log"
          - port: 80

  roles:
    - { role: uclalib_role_scl, when scl: True }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_php }
    - { role: uclalib_role_mysql, tags: ['client', 'server'], when: "{{ ansible_domain }}" != "library.ucla.edu" }
    - { role: uclalib_role_mysql, tags: ['client'], when: "{{ ansible_domain }}" == "library.ucla.edu" }
    - { role: uclalib_role_firewalld, when: "{{ ansible_domain }}" == "library.ucla.edu" }