- src: https://github.com/UCLALibrary/uclalib_role_apache
  version: vhost_optional

- src: https://github.com/UCLALibrary/uclalib_role_mysql.git

- src: https://github.com/UCLALibrary/uclalib_role_rhel7repos.git

- src: https://github.com/UCLALibrary/uclalib_role_php.git