---

- name: uclalib_ursusweb.yml
  become: yes
  become_method: sudo
  hosts: "[pstd]-w-ursus*"
  user: ansible

  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_samvera_basepackages }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_pip }
    - { role: uclalib_role_ruby }
    - { role: uclalib_role_passenger }
    - { role: uclalib_role_nodejs }
    - { role: uclalib_role_yarn }
    - { role: uclalib_role_redis }
    - { role: uclalib_role_blacklight_capdeploy }
