---

- name: uclalib_ursusmysql.yml
  become: yes
  become_method: sudo
  hosts: all
  user: ansible

  roles:
    - { role: uclalib_role_rhel8repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_mysql }
