---

- name: uclalib_ursussolr.yml
  become: yes
  become_method: sudo
  hosts: "[pstd]-u-calursussolr*"
  user: ansible

  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_java }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_solr }

  tasks:
    - name: Open firewall for web access
      firewalld:
        rich_rule: >
          rule family=ipv4 source address={{ item[1] }}/24 service name={{ item[0] }} accept
        permanent: true
        state: enabled
      loop: '{{ ["http", "https"] | product(["164.67.40.0", "164.67.48.0"]) | list }}'

