---

- name: uclalib_ursussolr.yml
  become: yes
  become_method: sudo
  hosts: "[pstd]-u-calursussolr*"
  user: ansible

  roles:
    - { role: uclalib_role_rhel8repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_java }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_solr }

  tasks:
    - name: Open firewall for web access
      firewalld:
        rich_rule: >
          rule family=ipv4 source address={{ item[1] }}/24 service name={{ item[0] }} accept
        immediate: true
        permanent: true
        state: enabled
      loop: '{{ ["http", "https"] | product(["164.67.40.0", "164.67.48.0"]) | list }}'

- name: uclalib_californicasolr.yml
  become: true
  become_method: sudo
  hosts: rsyncd
  user: ansible

  roles:
    - role: uclalib_role_rsyncd

  tasks:
    - name: Open firewall for rsync daemon access
      firewalld:
        rich_rule: >
          rule family=ipv4 source address=164.67.48.0/24 service name=rsyncd accept
        immediate: true
        permanent: true
        state: enabled

