---
- name: provision.yml
  become: yes
  become_method: sudo
  hosts: prod_kibana

  # Sensitive variables are stored locally on ansible server through a combination of host and group vars
  # Variables overrided include
  # rules_definitions
  # elasticsearch role variables
  vars:
    service_definitions:
      kibana_console_port:
        desc: "Kibana console port"
        proto: tcp
        port: 5601

  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_custom_facts }
    - { role: uclalib_role_rhelinsights }
    - { role: uclalib_role_firewalld }
    - { role: uclalib_role_kibana }
