---
name: avalon

services:
  avalon:
    image: avalonmediasystem/avalon:8.2
    depends_on:
      - redis
    volumes:
      - ./volumes/avalon/app/assets/:/home/app/avalon/app/assets/:ro
      - ./volumes/avalon/app/views/:/home/app/avalon/app/views/:ro
      - ./volumes/avalon/config:/home/app/avalon/config:ro
      - builds:/home/app/avalon/app/assets/builds:rw
      - masterfiles:/masterfiles
      - storage:/home/app/avalon/storage # Config another location in storage.yml
      - streaming:/streaming_derivatives

    environment:
      - APP_NAME
      - ASSET_HOST
      - DATABASE_URL
      - ENCODE_WORK_DIR
      - FEDORA_BASE_PATH
      - FEDORA_NAMESPACE
      - FEDORA_URL
      - MASTER_FILE_PATH
      - MEDIAINFO_PATH
      - NODE_OPTIONS
      - PIDFILE
      - PUMA_STATE_PATH
      - RAILS_ADDITIONAL_HOSTS
      - RAILS_ENV
      - RAILS_LOG_TO_STDOUT
      - RAILS_SERVE_STATIC_FILES
      - SAML_IDP_CERT
      - SAML_SP_CERT
      - SAML_SP_KEY
      - SECRET_KEY_BASE
      - SETTINGS__DOMAIN
      - SETTINGS__DROPBOX__PATH
      - SETTINGS__DROPBOX__UPLOAD_URI
      - SETTINGS__EMAIL__COMMENTS
      - SETTINGS__EMAIL__CONFIG__ADDRESS
      - SETTINGS__EMAIL__NOTIFICATION
      - SETTINGS__EMAIL__SUPPORT
      - SETTINGS__ENCODING__WORKING_FILE_PATH
      - SETTINGS__FFMPEG__PATH
      - SETTINGS__MASTER_FILE_MANAGEMENT__STRATEGY
      - SETTINGS__REDIS__URL
      - SETTINGS__STREAMING__AUTH_REFERER
      - SETTINGS__STREAMING__CONTENT_PATH
      - SETTINGS__STREAMING__HTTP_BASE
      - SETTINGS__STREAMING__SERVER
      - SETTINGS__STREAMING__STREAM_TOKEN_TTL
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL
      - SYSTEM_GROUPS
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
    command: bash -c "bundle exec rails assets:precompile && bundle exec rake db:migrate && bundle exec rails server -b 0.0.0.0"
  db:
    image: postgres:14-alpine
    volumes:
      - ./volumes/db/init-db:/docker-entrypoint-initdb.d:ro
      - db_data:/data
    environment:
      - AVALON_DB_PASSWORD
      - FEDORA_DB_PASSWORD
      - PGDATA
      - POSTGRES_HOST_AUTH_METHOD
      - POSTGRES_USER
  fedora:
    image: fcrepo/fcrepo:6-tomcat9
    volumes:
      - fedora_data:/data
    environment:
      - CATALINA_OPTS
      - FEDORA_ADMIN_PASSWORD
      - FEDORA_ADMIN_USERNAME
      - FEDORA_DB_PASSWORD
  redis:
    image: redis:alpine
  solr:
    image: solr:9
    volumes:
      - ./volumes/solr/conf:/opt/solr/avalon_conf:ro
      - solr_data:/var/solr
    environment:
      - SOLR_MODULES
    command:
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
  worker:
    command: bundle exec sidekiq -C config/sidekiq.yml
    extends: avalon
