---

- name: uclalib_californicaweb.yml
  become: yes
  become_method: sudo
  hosts: "[pstd]-w-californicaweb*"
  user: ansible

  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_samvera_basepackages }
    - { role: uclalib_role_java }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_certbot }
    - { role: uclalib_role_clamav }
    - { role: uclalib_role_pip }
    - { role: uclalib_role_imagemagick }
    - { role: uclalib_role_libreoffice }
    - { role: uclalib_role_ffmpeg }
    - { role: uclalib_role_fits }
    - { role: uclalib_role_ruby }
    - { role: uclalib_role_passenger }
    - { role: uclalib_role_nodejs }
    - { role: uclalib_role_yarn }
    - { role: uclalib_role_redis }
    - { role: uclalib_role_nfsmount }
    - { role: uclalib_role_samvera_capdeploy }

  tasks:
    - name: Open firewall for web access
      firewalld:
        service: '{{ item }}'
        permanent: true
        state: enabled
      loop:
        - http
        - https
