---

- name: uclalib_californicaweb.yml
  become: yes
  become_method: sudo
  hosts: "[pstd]-w-californica*"
  user: ansible

  roles:
    - { role: uclalib_role_epel, tags: [epel-role] }
    - { role: uclalib_role_uclalibrepo, tags: [uclalibrepo-role] }
    - { role: uclalib_role_samvera_basepackages, tags: [basepkgs-role] }
    - { role: uclalib_role_java, tags: [java-role] }
    - { role: uclalib_role_apache, tags: [apache-role] }
    - { role: uclalib_role_certbot, tags: [certbot-role] }
    - { role: uclalib_role_clamav, tags: [clamav-role] }
    - { role: uclalib_role_pip, tags: [pip-role] }
    - { role: uclalib_role_imagemagick, tags: [imagemagick-role] }
    - { role: uclalib_role_libreoffice, tags: [libreoffice-role] }
    - { role: uclalib_role_ffmpeg, tags: [ffmpeg-role] }
    - { role: uclalib_role_fits, tags: [fits-role] }
    - { role: uclalib_role_ruby, tags: [ruby-role] }
    - { role: uclalib_role_passenger, tags: [passenger-role] }
    - { role: uclalib_role_nodejs, tags: [nodejs-role] }
    - { role: uclalib_role_yarn, tags: [yarn-role] }
    - { role: uclalib_role_redis, tags: [redis-role] }
    - { role: uclalib_role_nfsmount, tags: [nfsmount-role] }
    - { role: uclalib_role_samvera_capdeploy, tags: [capdeploy-role] }

  tasks:
    - name: Open firewall for web access
      firewalld:
        service: '{{ item }}'
        permanent: true
        state: enabled
      loop:
        - http
        - https
