---

- hosts: "californica{{ californica_env | default('None') }}fedora"
  become: yes
  become_method: sudo
  user: ansible

  tasks:
    - name: Stop Apache HTTPD
      service:
        name: httpd
        state: stopped

    - name: Stop Fedora
      service:
        name: fedora
        state: stopped

    - name: Create empty temp directory
      file:
        path: "/tmp/empty"
        owner: "fedora"
        group: "fedora"
        mode: "0755"
        state: "directory"

    - name: Delete all contents of the fedora-data directory
      command: >
        rsync -a --delete --exclude=.snapshot /tmp/empty/ /opt/fedora-data/

    - name: Remove empty temp directory
      file:
        path: "/tmp/empty"
        state: "absent"

    - name: Drop MODESHAPE_REPOSITORY table in the fedora database
      command: >
        mysql --defaults-file=/root/.my.fedora.cnf -e "DROP TABLE MODESHAPE_REPOSITORY"

    - name: Start Fedora
      service:
        name: fedora
        state: started

    - name: Start Apache HTTPD
      service:
        name: httpd
        state: started

##############################################################################

- hosts: "californica{{ californica_env | default('None') }}web"
  become: yes
  become_method: sudo
  user: ansible

  tasks:
    - name: Stop Apache HTTPD
      service:
        name: httpd
        state: stopped

    - name: Delete all content from the Solr index
      command: >
        curl {{ solr_index_url }}/update?commit=true -H "Content-Type: text/xml" --data-binary '<delete><query>*:*</query></delete>'

    - name: Delete all content in Redis
      command: >
        redis-cli FLUSHALL

    - name: Reset the Rails application database
      become_user: "{{ capistrano_user | default('deploy') }}"
      shell: >
        DISABLE_DATABASE_ENVIRONMENT_CHECK=1 RAILS_ENV=production bundle exec rake db:reset
      args:
        chdir: "/opt/{{ project_name }}/current"

    - name: Start Apache HTTPD
      service:
        name: httpd
        state: started
