---

- name: uclalib_californicafedora.yml
  become: yes
  become_method: sudo
  hosts: "[pstd]-u-californicafedora*"
  user: ansible

  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_java }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_tomcat }
    - { role: uclalib_role_nfsmount }
    - { role: uclalib_role_fedora4 }
