---

- name: uclalib_californicamysql.yml
  become: yes
  become_method: sudo
  hosts: all
  user: ansible
  vars:
    project_name: californica
    env_name: test

  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_mysql }
