---

- name: uclalib_californicasolr.yml
  become: yes
  become_method: sudo
  hosts: "[pstd]-u-calursussolr*"
  user: ansible

  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_java }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_solr }


- name: uclalib_californicasolr.yml
  become: true
  become_method: sudo
  hosts: rsyncd
  user: ansible

  roles:
    - role: uclalib_role_rsyncd
