---
- name: lib_solr.yml
  become: yes
  become_method: sudo
  hosts: all

  roles:
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_java }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_solr }