---

- name: lib_web.yml
  become: true
  become_method: sudo
  hosts: all

  vars:
    ffmpeg_download_url: http://pkgs.library.ucla.edu/ffmpeg/ffmpeg-4.1-64bit-static.tar.xz

  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_java, openjdk_java_version: '1.8.0' }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_ffmpeg }
    - { role: uclalib_role_ruby, ruby_version: '2.5.1' }
    - { role: uclalib_role_passenger, passenger_version: '5.3.3' }
    - { role: uclalib_role_redis }
    - { role: uclalib_role_avalonrails }
