---
# https://docs.docker.com/engine/install/rhel/ 2026-06-11
- name: "Install Docker Engine (Community Edition)"
  hosts: "*avalon*"
  become: true

  vars:
    docker_incompatible_packages:
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-engine
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - podman
      - runc
    docker_prerequisite_packages:
      - dnf-plugins-core
    docker_repo: https://download.docker.com/linux/rhel/docker-ce.repo
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  tasks:
    - name: Remove docker_incompatible_packages
      package:
        name: "{{ docker_incompatible_packages }}"
        state: absent

    - name: Add docker_prerequisite_packages
      package:
        name: "{{ docker_prerequisite_packages }}"
        state: present

    - name: Add docker_repo
      command:
        argv:
          - /usr/bin/dnf
          - config-manager
          - --add-repo
          - "{{ docker_repo }}"
        creates: /etc/yum.repos.d/{{ docker_repo | basename }}

    - name: Install docker_packages
      package:
        name: "{{ docker_packages }}"
        state: present

    - name: Enable docker service
      service:
        name: docker
        enabled: true

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Create docker user groups
      group:
        name: '{{ item }}' 
        state: present
        system: yes
      loop: '{{ docker_users }}'

    - name: Create docker users
      user:
        name: '{{ item }}'
        comment: '{{ item }}'
        create_home: true
        group: '{{ item }}'
        groups:
          - docker
        home: '/var/lib/{{ item }}'
        password: '!'
        shell: '/usr/bin/bash' # /usr/bin/bash is what is in the rpm
        state: present
      loop: '{{ docker_users }}'

    - name: Add deploy keys
      authorized_key:
        user: '{{ item[0] }}'
        key: '{{ item[1] }}'
      loop: '{{ docker_users | product(docker_deploy_keys) | list }}'
      when: docker_deploy_keys is defined

    - name: Add volume mount points
      mount:
        path: /srv/{{ item }}
        state: mounted
        fstype: xfs
        src: 'LABEL={{ item | upper }}'
      loop: '{{ avalon_mounts }}'

