---

- name: lib_web.yml
  become: yes
  become_method: sudo
  hosts: "[dp]-w-avalonaweb*"

  roles:
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_samvera_basepackages } # Update this role to support RHEL8 - adjust package list for RHEL8
    - { role: uclalib_role_java }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_pip }
    - { role: uclalib_role_imagemagick }
    - { role: uclalib_role_ffmpeg }
    - { role: uclalib_role_ruby } # Update this role to support RHEL8 - need to build rpm of ruby for RHEL8
    - { role: uclalib_role_passenger } # Update this role to support RHEL8 - set passenger version to 6.0.20
    - { role: uclalib_role_nodejs }
    - { role: uclalib_role_yarn }
    - { role: uclalib_role_redis }
#    - { role: uclalib_role_samvera_capdeploy }