---

- name: Install Apache
  hosts: ?-u-avalonfedora??.library.ucla.edu
  become: true

  roles:
    - role: uclalib_role_apache

  tasks:
    - name: Install Apache vhost
      template:
        src: httpd/fedora.conf.j2
        dest: /etc/httpd/vhosts.d/fedora.conf
        owner: root
        group: root
        mode: '0444'
      notify: Restart Apache Webserver Service

    - name: Make Fedora Web Log Directory
      file:
        path: /var/log/httpd/fedora
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Enable Apache Webserver
      service:
        name: httpd
        enabled: true
        state: started

    - name: Install import/export jar
      get_url:
        url: http://pkgs.library.ucla.edu/fedora/{{ item }}-{{ avalon_fedora_import_export_version }}.jar
        # XDG_DATA_HOME
        dest: .local/share/{{ item }}.jar
        checksum: sha256:http://pkgs.library.ucla.edu/fedora/SHA256SUMS
        mode: '0555'
      become: true
      become_user: fedora
      loop:
        - fcrepo-import-export

    - name: Install Fedora Commons Backup Script
      copy:
        src: fedora/{{ item }}
        # XDG_BIN_HOME
        dest: .local/bin/{{ item }}
        mode: '0555'
      become: true
      become_user: fedora
      loop:
        - fedora-backup

  handlers:
    - name: Restart Apache Webserver Service
      service:
        name: httpd
        state: restarted
