---

- name: uclalib_oral-history_solr6.yml
  hosts: ?-u-ohsolr??.library.ucla.edu
  become: yes
  become_method: sudo
  user: ansible

  roles:
  - { role: uclalib_role_rhel7repos }
  - { role: uclalib_role_epel }
  - { role: uclalib_role_uclalibrepo }
  - { role: uclalib_role_java }
  - { role: uclalib_role_apache }
  - { role: uclalib_role_solr7 }
