---

- name: uclalib_oral-history_pgsql.yml
  hosts: oralhistory_*
    # --limit must specify the whole name:
    # --limit oralhistory_test
    # --limit oralhistory_prod
  become: true
  vars_files:
    - ../../group_vars/{{ ansible_limit }}/main.yml
    - ../../group_vars/{{ ansible_limit }}/main.vault.yml

  roles:
    - role: uclalib_role_postgresql
      delegate_to: "{{ pgsql_host }}"
