- name: drupal_deploy_post.yml
  hosts: all

  vars:
    drush_path: /usr/local/bin/drush
    drush_user: druadmin
    drush_configs:
      test_www:
        drush_alias: test-www
      stage_www:
        drush_alias: stage-www
      prod_www:
        drush_alias: prod-www

  tasks:
    - name: "Drush trigger updatedb on {{ APP_ENV }}"
      shell: |
        "{{ drush_path }}" @"{{ drush_configs[APP_ENV]['drush_alias'] }}" updatedb -y
      become: yes
      become_user: "{{ drush_user }}"
    - name: "Drush trigger cache clear on {{ APP_ENV }}"
      shell: |
        "{{ drush_path }}" @"{{ drush_configs[APP_ENV]['drush_alias'] }}" cc all
      become: yes
      become_user: "{{ drush_user }}"
    - name: "Drush trigger features revert on {{ APP_ENV }}"
      shell: |
        "{{ drush_path }}" @"{{ drush_configs[APP_ENV]['drush_alias'] }}" features-revert-all -y
      become: yes
      become_user: "{{ drush_user }}"
    - name: "Drush trigger cache clear on {{ APP_ENV }}"
      shell: |
        "{{ drush_path }}" @"{{ drush_configs[APP_ENV]['drush_alias'] }}" cc all
      become: yes
      become_user: "{{ drush_user }}"
    - name: "Bring {{ APP_ENV }} out of maintenance mode"
      shell: |
        "{{ drush_path }}" @"{{ drush_configs[APP_ENV]['drush_alias'] }}" vset maintenance_mode 0
      become: yes
      become_user: "{{ drush_user }}"
    - name: "Drush trigger cache clear on {{ APP_ENV }}"
      shell: |
        "{{ drush_path }}" @"{{ drush_configs[APP_ENV]['drush_alias'] }}" cc all
      become: yes
      become_user: "{{ drush_user }}"
