- name: drupal_stage-www_refresh.yml
  hosts: all

  vars:
    drush_path: /usr/local/bin/drush
    drush_user: druadmin
    drupal_backupdir: /drupalbackups
    drupal_sites_default_files_dir: /var/www/vhosts/webhead/sites_default_files
    drupal_sourcecode_dir: /var/www/vhosts/webhead/drupal
    drupal_sites_default_files_latest_symlink: "{{ drupal_backupdir }}/dumps/{{ drush_configs[APP_ENV]['drush_alias'] }}_latest-sites-default-files.tar.gz"
    drupal_sql_file_latest_symlink: "{{ drupal_backupdir }}/dumps/{{ drush_configs[APP_ENV]['drush_alias'] }}_latest-db.sql.gz"
    drupal_sync_scratch_path: /tmp/sync-scratch
    drush_configs:
      test_www:
        drush_alias: test-www
      stage_www:
        drush_alias: stage-www
      prod_www:
        drush_alias: prod-www

  tasks:
    - name: "Drush drop {{ APP_ENV }} mysql tables"
      shell: |
             "{{ drush_path }}" @"{{ drush_configs[APP_ENV]['drush_alias'] }}" sql-drop -y
      become: yes
      become_user: "{{ drush_user }}"

    - name: "Create scratch space for syncing static files"
      file:
        path: "{{ drupal_sync_scratch_path }}"
      become: yes
      become_user: "{{ drush_user }}"

    - name: "Extract latest sites_default_files backup into temporary location"
      shell: |
             tar -zxf "{{ drupal_sites_default_files_latest_symlink }}/" -C "{{ drupal_sync_scratch_path }}"

    - name: "Sync extracted files into {{ drupal_sites_default_files_dir }} on {{ APP_ENV }}"
      shell: |
             rsync -av --progress "{{ drupal_sync_scratch_path }}"/ "{{ drupal_sites_default_files_dir }}"/

    - name: "Copy and extract latest database dump to scratch space"
      shell: |
             cp -L "{{ drupal_sql_file_latest_symlink }}" "{{ drupal_sync_scratch_path }}"
             gunzip "{{ drupal_sync_scratch_path }}"/"{{ drush_configs[APP_ENV]['drush_alias'] }}"_latest-db.sql.gz
      become: yes 
      become_user: "{{ drush_user }}"

    - name: "Import extracted latest database dump on {{ APP_ENV }}"
      shell: |
             `"{{ drush_path }} @"{{ drush_configs[APP_ENV]['drush_alias'] }}" sql-connect` < "{{ drupal_sync_scratch_path }}"/"{{ drush_configs[APP_ENV]['drush_alias'] }}"_latest-db.sql
      become: yes 
      become_user: "{{ drush_user }}"

    - name: "Cleaning up scratch space on {{ APP_ENV }}"
      shell: |
             rm -rf "{{ drupal_sync_scratch_path }}"

    - name: "Drush trigger cache clear on {{ APP_ENV }}"
      shell: |
             "{{ drush_path }}" @"{{ drush_configs[APP_ENV]['drush_alias'] }}" cc all